import os
import glob
import subprocess
import sys
import git

def is_path_safe(path):
    """
    Returns True if a path is safe to read.

    Checks for absolute paths or directory traversal.

    >>> is_path_safe('README.md')
    True
    >>> is_path_safe('chat.py')
    True
    >>> is_path_safe('/etc/passwd')
    False
    >>> is_path_safe('../secret.txt')
    False
    >>> is_path_safe('some/../file.txt')
    False
    >>> is_path_safe('.')
    True
    >>> is_path_safe('')
    True
    """
    if path.startswith('/'):
        return False
    parts = path.replace('\\', '/').split('/')
    if '..' in parts:
        return False
    return True


def ls(path='.'):
    """
    List files/folders in a directory, asciibetically, one per line.

    Each entry is just the base name (not the full path). Unsafe paths
    (absolute or containing '..') return an error string instead.

    >>> result = ls('.')
    >>> result.split('\\n') == sorted(result.split('\\n'))
    True
    >>> ls('/etc')
    'Error: unsafe path'
    >>> ls('../other')
    'Error: unsafe path'
    >>> ls('nonexistent_folder_xyz')
    ''
    
    # Tests the default argument fallback
    >>> ls() == ls('.')
    True
    
    >>> '/' not in ls()
    True
    """
    if not is_path_safe(path):
        return 'Error: unsafe path'
    files = sorted(glob.glob(f'{path}/*'))
    names = [os.path.basename(f) for f in files]
    return '\n'.join(names)

def cat(path):
    """
    Open a file and return its contents as a string.

    >>> cat('nonexistent_file_xyz.txt')
    'Error: file not found'
    >>> cat('/etc/passwd')
    'Error: unsafe path'
    >>> cat('../secret.txt')
    'Error: unsafe path'
    
    # 1. Test standard UTF-8 success
    >>> with open('test_cat_utf8.txt', 'w', encoding='utf-8') as f:
    ...     _ = f.write('hello world')
    >>> cat('test_cat_utf8.txt')
    'hello world'
    
    # 2. Test UnicodeDecodeError fallback to UTF-16 success
    >>> with open('test_cat_utf16.txt', 'w', encoding='utf-16') as f:
    ...     _ = f.write('hello utf16')
    >>> cat('test_cat_utf16.txt')
    'hello utf16'
    
    # 3. Test complete decode failure (invalid binary data)
    >>> with open('test_cat_binary.bin', 'wb') as f:
    ...     _ = f.write(b'\\x80\\x81\\xff') 
    >>> cat('test_cat_binary.bin')
    'Error: cannot decode file'

    # 4. Test general Exception catch (e.g., trying to read a directory)
    # This raises IsADirectoryError or PermissionError depending on the OS.
    >>> result = cat('.')
    >>> result.startswith('Error: [Errno')
    True

    # Cleanup the test files
    >>> os.remove('test_cat_utf8.txt')
    >>> os.remove('test_cat_utf16.txt')
    >>> os.remove('test_cat_binary.bin')
    """
    if not is_path_safe(path):
        return 'Error: unsafe path'
    try:
        with open(path, 'r', encoding='utf-8') as f:
            return f.read()
    except FileNotFoundError:
        return 'Error: file not found'
    except UnicodeDecodeError:
        try:
            with open(path, 'r', encoding='utf-16') as f:
                return f.read()
        except Exception:
            return 'Error: cannot decode file'
    except Exception as e:
        return f'Error: {e}'
    

######## PROJECT 4 ##########
def doctests(path):
    """
    Run doctests (with --verbose flag) on a Python file and return output.

    >>> doctests('/etc/passwd')
    'Error: unsafe path'
    >>> doctests('../secret.py')
    'Error: unsafe path'
    >>> doctests('nonexistent_xyz.py')
    'Error: file not found'


    # Setup: Create a temporary Python file with a simple doctest
    >>> with open('test_dummy_doctest.py', 'w', encoding='utf-8') as f:
    ...     _ = f.write("def dummy():\\n    '''\\n    >>> 1 + 1\\n    2\\n    '''\\n    pass\\n")

    # 1. Test successful execution of the subprocess block
    # We check for strings generated by Python's 'doctest -v' command
    >>> output = doctests('test_dummy_doctest.py')
    >>> 'Trying:' in output
    True
    >>> '1 + 1' in output
    True
    >>> 'ok' in output or 'passed' in output.lower()
    True

    # Cleanup: Remove the temporary file
    >>> os.remove('test_dummy_doctest.py')
    """
    if not is_path_safe(path):
        return 'Error: unsafe path'
    if not os.path.isfile(path):
        return 'Error: file not found'
    result = subprocess.run(
        [sys.executable, '-m', 'doctest', '-v', path],
        capture_output=True,
        text=True,
    )
    return result.stdout + result.stderr


def write_files(files, commit_message):
    """
    Write multiple files and commit them all in one git commit.

    Each item in files must be a dict with 'path' and 'contents' keys.
    Returns an error string if any path is unsafe, otherwise returns
    a success message plus doctest output for any Python files written.

    >>> write_files([{'path': '/etc/foo', 'contents': 'x'}], 'msg')
    'Error: unsafe path: /etc/foo'
    >>> write_files([{'path': '../foo.py', 'contents': 'x'}], 'msg')
    'Error: unsafe path: ../foo.py'
    """
    for f in files:
        if not is_path_safe(f['path']):
            return f'Error: unsafe path: {f["path"]}'

    output_parts = []
    for f in files:
        os.makedirs(os.path.dirname(f['path']) or '.', exist_ok=True)
        with open(f['path'], 'w', encoding='utf-8') as fh:
            fh.write(f['contents'])
        output_parts.append(f'Written: {f["path"]}')

    try:
        repo = git.Repo('.')
        paths = [f['path'] for f in files]
        repo.index.add(paths)
        repo.index.commit(f'[docchat] {commit_message}')
    except Exception as e:
        output_parts.append(f'Git error: {e}')
        return '\n'.join(output_parts)

    for f in files:
        if f['path'].endswith('.py'):
            output_parts.append(f'Doctest output for {f["path"]}:')
            output_parts.append(doctests(f['path']))

    return '\n'.join(output_parts)


def write_file(path, contents, commit_message):
    """
    Write contents to a single file and commit the change to git.

    This is a thin wrapper around write_files. If the file is a Python
    file, doctests are run after writing and the output is returned.

    >>> write_file('/etc/foo', 'x', 'msg')
    'Error: unsafe path: /etc/foo'
    >>> write_file('../foo.py', 'x', 'msg')
    'Error: unsafe path: ../foo.py'

    >>> import os, subprocess
    >>> result = write_file('test_wrapper_file.txt', 'hello world', 'test commit')
    >>> 'Written: test_wrapper_file.txt' in result
    True
    >>> os.path.isfile('test_wrapper_file.txt')
    True
    >>> subprocess.run(['git', 'rm', 'test_wrapper_file.txt'], capture_output=True)  # doctest: +ELLIPSIS
    CompletedProcess(...)
    >>> subprocess.run(['git', 'commit', '-m', 'cleanup test file'], capture_output=True)  # doctest: +ELLIPSIS
    CompletedProcess(...)

    >>> result = write_file('test_wrapper_file.py', 'def f():\\n    pass\\n', 'py test commit')
    >>> 'Written: test_wrapper_file.py' in result
    True
    >>> os.path.isfile('test_wrapper_file.py')
    True
    >>> subprocess.run(['git', 'rm', 'test_wrapper_file.py'], capture_output=True)  # doctest: +ELLIPSIS
    CompletedProcess(...)
    >>> subprocess.run(['git', 'commit', '-m', 'cleanup test py file'], capture_output=True)  # doctest: +ELLIPSIS
    CompletedProcess(...)
    """
    return write_files(
        [{'path': path, 'contents': contents}],
        commit_message,
    )


def rm(path):
    """
    Delete a file (supports globs) and commit the removal to git.

    >>> rm('/etc/passwd')
    'Error: unsafe path'
    >>> rm('../secret.txt')
    'Error: unsafe path'
    >>> rm('nonexistent_xyz.txt')
    'Error: no files matched: nonexistent_xyz.txt'

    >>> import os, subprocess
    >>> with open('test_rm_file.txt', 'w') as f:
    ...     _ = f.write('hello')
    >>> os.path.isfile('test_rm_file.txt')
    True
    >>> subprocess.run(['git', 'add', 'test_rm_file.txt'], capture_output=True)  # doctest: +ELLIPSIS
    CompletedProcess(...)
    >>> result = rm('test_rm_file.txt')
    >>> result.startswith('Deleted:')
    True
    >>> os.path.isfile('test_rm_file.txt')
    False
    """
    if not is_path_safe(path):
        return 'Error: unsafe path'

    matched = glob.glob(path)
    if not matched:
        return f'Error: no files matched: {path}'

    removed = []
    for filepath in matched:
        try:
            os.remove(filepath)
            removed.append(filepath)
        except Exception as e:
            return f'Error deleting {filepath}: {e}'

    try:
        repo = git.Repo('.')
        repo.index.remove(removed)
        repo.index.commit(f'[docchat] rm {path}')
    except Exception as e:
        return f'Files deleted but git error: {e}'

    return f'Deleted: {", ".join(removed)}'